apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: come-test-tha
resources:
  - ../../base
commonLabels:
  market: tha
images:
  - name: public.ecr.aws/docker/library/nginx
    newName: public.ecr.aws/docker/library/nginx
    newTag: alpine
