apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-onboarded
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/priyankaajbhagatt-collab/argocd-apps.git
    targetRevision: main
    path: apps
    directory:
      recurse: false
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
