apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backstage-onboarded
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/priyankaajbhagatt-collab/argocd-apps.git
        revision: main
        files:
          - path: "apps/*.yaml"
  template:
    metadata:
      name: "{{ path.basenameNormalized }}"
    spec:
      project: default
      source:
        repoURL: "{{ source.repoURL }}"
        targetRevision: "{{ source.targetRevision }}"
        path: "{{ source.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ destination.namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
