apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: v6commerce-cart-app-service-can
resources:
  - ../../base
commonLabels:
  market: can
images:
  - name: public.ecr.aws/docker/library/nginx
    newName: public.ecr.aws/docker/library/nginx
    newTag: alpine
