apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: v6commerce-cart-app-service-prod
resources:
  - ../../base
commonLabels:
  env: prod
  region: us-east-1
# The deploy stage of the CodePipeline runs:
#   argocd app set v6commerce-cart-app-service-prod-us-east-1 --kustomize-image v6commerce-cart-app-service=<ecr-uri>:<sha>
# which rewrites this block at deploy time.
images:
  - name: public.ecr.aws/docker/library/nginx
    newName: public.ecr.aws/docker/library/nginx
    newTag: alpine
