apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: check-d1-mex
  namespace: argocd
  labels:
    service: check-d1
    market: mex
    group: commerce-orderas
    managed-by: backstage-scaffolder
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/priyankaajbhagatt-collab/check-d1.git
    targetRevision: main
    path: deploy/overlays/mex

  destination:
    server: https://kubernetes.default.svc
    namespace: check-d1-mex

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
