apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: e2e-gha-1778485483-usa
  namespace: argocd
  labels:
    service: e2e-gha-1778485483
    market: usa
    group: commerce-orderas
    managed-by: backstage-scaffolder
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/priyankaajbhagatt-collab/e2e-gha-1778485483.git
    targetRevision: main
    path: deploy/overlays/usa

  destination:
    server: https://kubernetes.default.svc
    namespace: e2e-gha-1778485483-usa

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
