apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: insights-api-can
  namespace: argocd
  labels:
    service: insights-api
    market: can
    group: commerce-orderas
    managed-by: backstage-scaffolder
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/priyankaajbhagatt-collab/insights-api.git
    targetRevision: main
    path: deploy/overlays/can

  destination:
    server: https://kubernetes.default.svc
    namespace: insights-api-can

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
