apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: v2commerce-cart-app-service-vnm
resources:
  - ../../base
commonLabels:
  market: vnm
images:
  - name: public.ecr.aws/docker/library/nginx
    newName: public.ecr.aws/docker/library/nginx
    newTag: alpine
